const cfg=window.APP_CONFIG;const $=id=>document.getElementById(id);const ADMIN_CACHE_KEY='liuheAdminDashboardCacheV2';const savedAdminToken=localStorage.getItem('liuheAdminToken')||sessionStorage.getItem('liuheAdminToken')||'';if(savedAdminToken)localStorage.setItem('liuheAdminToken',savedAdminToken);sessionStorage.removeItem('liuheAdminToken');const state={token:savedAdminToken,orders:[],filter:'waiting',query:''};const money=n=>`NT$${Number(n||0).toLocaleString('zh-TW')}`;
async function api(action,payload={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(cfg.API_BASE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload}),signal:controller.signal});const d=await r.json();if(!r.ok||!d.ok){const error=new Error(d?.error?.message||'連線失敗');error.code=d?.error?.code||'';throw error}return d.result}catch(error){if(error.name==='AbortError')throw new Error('伺服器回應逾時，畫面已保留，可稍後再按重新整理。');throw error}finally{clearTimeout(timer)}}
function group(status){if(status==='已取消')return'cancelled';if(status==='已出貨'||status==='已完成')return'shipped';return'waiting'}
function label(status){return group(status)==='waiting'?'已收到訂單・等待出貨':group(status)==='shipped'?'已出貨':'已取消'}
async function login(e){e.preventDefault();$('loginError').textContent='';const button=e.currentTarget.querySelector('button[type="submit"]');setBusy(button,true,'登入中');try{const result=await api('adminLogin',{pin:new FormData(e.currentTarget).get('pin')});state.token=result.adminToken;localStorage.setItem('liuheAdminToken',state.token);showDashboard(result.dashboard)}catch(err){$('loginError').textContent=err.message}finally{setBusy(button,false)}}
async function refresh(options={}){const silent=Boolean(options.silent),force=Boolean(options.force);const button=$('refreshButton');if(!silent)setBusy(button,true,'同步中');try{showDashboard(await api('adminRefresh',{adminToken:state.token,force}),true)}catch(err){if(['SESSION_INVALID','SESSION_EXPIRED'].includes(err.code))logout();else toast(err.message,true)}finally{if(!silent)setBusy(button,false)}}
function saveDashboard(){try{localStorage.setItem(ADMIN_CACHE_KEY,JSON.stringify({savedAt:Date.now(),orders:state.orders}))}catch(_){}}
function loadDashboard(){try{const data=JSON.parse(localStorage.getItem(ADMIN_CACHE_KEY)||'null');return data&&Array.isArray(data.orders)?data:null}catch(_){return null}}
function showDashboard(data,keep=true){state.orders=data.orders||[];saveDashboard();$('loginPanel').hidden=true;$('dashboard').hidden=false;$('logoutButton').hidden=false;$('passwordButton').hidden=false;$('lastSync').textContent=`最近同步：${new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}`;const counts={waiting:0,shipped:0,cancelled:0};state.orders.forEach(o=>counts[group(o.status)]++);$('stats').innerHTML=`<div class="stat"><span>等待出貨</span><strong>${counts.waiting}</strong></div><div class="stat"><span>已出貨</span><strong>${counts.shipped}</strong></div><div class="stat"><span>已取消</span><strong>${counts.cancelled}</strong></div>`;render()}
function patchOrder(orderNo,changes){const order=state.orders.find(item=>item.orderNo===orderNo);if(!order)return;Object.assign(order,changes);showDashboard({orders:state.orders})}
function render(){const query=state.query.trim().toLowerCase();const list=state.orders.filter(o=>group(o.status)===state.filter).filter(o=>!query||[o.orderNo,o.customerName,o.phone,o.trackingNo,o.itemsSummary].some(value=>String(value||'').toLowerCase().includes(query)));$('orderCount').textContent=`共 ${list.length} 筆訂單`;$('orders').innerHTML=list.length?list.map(card).join(''):`<div class="empty">${query?'找不到符合搜尋的訂單':'目前沒有這個狀態的訂單'}</div>`;document.querySelectorAll('[data-filter]').forEach(b=>b.dataset.active=String(b.dataset.filter===state.filter))}
function card(o){const g=group(o.status),address=o.delivery==='7-11超商取貨'?`${o.storeName}門市 ${o.storeCode}・${o.storeAddress}`:o.homeAddress;return `<article class="order ${g}" data-order="${esc(o.orderNo)}"><div class="order-top"><h2>${esc(o.orderNo)}</h2><span class="status">${label(o.status)}</span></div><div class="order-meta"><span>${esc(o.createdAt)}</span><span>${esc(o.delivery)}</span><strong>${money(o.total)}</strong></div><div class="customer"><span>收件人：${esc(o.customerName)}</span><span>電話：<a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></span><span>${esc(address)}</span></div><p class="items">${esc(o.itemsSummary||'商品明細未載入')}</p>${o.note?`<p>備註：${esc(o.note)}</p>`:''}${g==='waiting'?`<div class="actions"><div class="ship-row"><input class="tracking-input" placeholder="輸入物流單號（必填）" autocomplete="off"><button class="ship-button" data-ship>確認出貨</button></div><div class="cancel-row"><input class="reason-input" placeholder="取消原因（選填）"><button class="cancel-button" data-cancel>取消訂單</button></div></div>`:g==='shipped'?`<div class="tracking">出貨時間：${esc(o.shippedAt||'')}</div><div class="actions tracking-edit"><div class="ship-row"><input class="tracking-edit-input" value="${esc(o.trackingNo||'')}" placeholder="輸入正確物流單號" autocomplete="off"><button class="ship-button" data-update-tracking>修改單號</button></div><small>修改後，買家的「我的訂單」會同步顯示新單號。</small></div>`:''}</article>`}
async function ship(article){const trackingNo=article.querySelector('.tracking-input').value.trim();if(trackingNo.length<4)return toast('請先輸入完整物流單號。',true);const button=article.querySelector('[data-ship]');setBusy(button,true,'處理中');try{const r=await api('adminShipOrder',{adminToken:state.token,orderNo:article.dataset.order,trackingNo});patchOrder(article.dataset.order,{status:r.status||'已出貨',trackingNo:r.trackingNo||trackingNo,shippedAt:new Date().toLocaleString('zh-TW',{hour12:false})});toast(r.message)}catch(err){toast(err.message,true)}finally{setBusy(button,false)}}
async function updateTracking(article){const trackingNo=article.querySelector('.tracking-edit-input').value.trim();if(trackingNo.length<4)return toast('請輸入完整物流單號。',true);if(!window.confirm(`確定將 ${article.dataset.order} 的物流單號修改為 ${trackingNo}？`))return;const button=article.querySelector('[data-update-tracking]');setBusy(button,true,'更新中');try{const r=await api('adminUpdateTracking',{adminToken:state.token,orderNo:article.dataset.order,trackingNo});patchOrder(article.dataset.order,{trackingNo:r.trackingNo||trackingNo});toast(r.message)}catch(err){toast(err.message,true)}finally{setBusy(button,false)}}
async function cancel(article){const reason=article.querySelector('.reason-input').value.trim();if(!window.confirm(`確定要取消訂單 ${article.dataset.order}？取消後會回補庫存。`))return;const button=article.querySelector('[data-cancel]');setBusy(button,true,'取消中');try{const r=await api('adminCancelOrder',{adminToken:state.token,orderNo:article.dataset.order,reason});patchOrder(article.dataset.order,{status:r.status||'已取消'});toast(r.message)}catch(err){toast(err.message,true)}finally{setBusy(button,false)}}
function toast(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error-toast',error);$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,3200)}function logout(){state.token='';localStorage.removeItem('liuheAdminToken');sessionStorage.removeItem('liuheAdminToken');localStorage.removeItem(ADMIN_CACHE_KEY);$('dashboard').hidden=true;$('logoutButton').hidden=true;$('passwordButton').hidden=true;$('loginPanel').hidden=false}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openPassword(){$('passwordError').textContent='';$('passwordForm').reset();$('passwordDialog').showModal()}
function setBusy(button,busy,label){if(busy){button.dataset.label=button.textContent;button.disabled=true;button.classList.add('is-loading');button.textContent=label}else{button.disabled=false;button.classList.remove('is-loading');button.textContent=button.dataset.label||button.textContent;delete button.dataset.label}}
async function changePassword(e){e.preventDefault();$('passwordError').textContent='';const values=Object.fromEntries(new FormData(e.currentTarget).entries());if(values.newPin!==values.confirmPin){$('passwordError').textContent='兩次輸入的新密碼不一致。';return}const button=e.currentTarget.querySelector('.password-submit');setBusy(button,true,'修改中');try{const result=await api('adminChangePassword',{adminToken:state.token,...values});$('passwordDialog').close();logout();$('loginError').textContent=result.message}catch(err){$('passwordError').textContent=err.message}finally{setBusy(button,false)}}
$('loginForm').addEventListener('submit',login);$('refreshButton').addEventListener('click',()=>refresh({force:true}));$('orderSearch').addEventListener('input',e=>{state.query=e.target.value;render()});$('logoutButton').addEventListener('click',logout);$('passwordButton').addEventListener('click',openPassword);$('passwordClose').addEventListener('click',()=>$('passwordDialog').close());$('passwordForm').addEventListener('submit',changePassword);document.querySelector('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;render()});$('orders').addEventListener('click',e=>{const a=e.target.closest('.order');if(!a)return;if(e.target.closest('[data-ship]'))ship(a);if(e.target.closest('[data-update-tracking]'))updateTracking(a);if(e.target.closest('[data-cancel]'))cancel(a)});if(state.token){const cached=loadDashboard();if(cached)showDashboard(cached);refresh({silent:Boolean(cached)})}
