const cfg=window.APP_CONFIG;const $=id=>document.getElementById(id);const state={token:sessionStorage.getItem('liuheAdminToken')||'',orders:[],filter:'waiting'};const money=n=>`NT$${Number(n||0).toLocaleString('zh-TW')}`;
async function api(action,payload={}){const r=await fetch(cfg.API_BASE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.error?.message||'連線失敗');return d.result}
function group(status){if(status==='已取消')return'cancelled';if(status==='已出貨'||status==='已完成')return'shipped';return'waiting'}
function label(status){return group(status)==='waiting'?'已收到訂單・等待出貨':group(status)==='shipped'?'已出貨':'已取消'}
async function login(e){e.preventDefault();$('loginError').textContent='';const button=e.currentTarget.querySelector('button[type="submit"]');setBusy(button,true,'登入中');try{const result=await api('adminLogin',{pin:new FormData(e.currentTarget).get('pin')});state.token=result.adminToken;sessionStorage.setItem('liuheAdminToken',state.token);showDashboard(result.dashboard)}catch(err){$('loginError').textContent=err.message}finally{setBusy(button,false)}}
async function refresh(){try{showDashboard(await api('adminRefresh',{adminToken:state.token}),true)}catch(err){logout();toast(err.message,true)}}
function showDashboard(data,keep=true){state.orders=data.orders||[];$('loginPanel').hidden=true;$('dashboard').hidden=false;$('logoutButton').hidden=false;$('passwordButton').hidden=false;const counts={waiting:0,shipped:0,cancelled:0};state.orders.forEach(o=>counts[group(o.status)]++);$('stats').innerHTML=`<div class="stat"><span>等待出貨</span><strong>${counts.waiting}</strong></div><div class="stat"><span>已出貨</span><strong>${counts.shipped}</strong></div><div class="stat"><span>已取消</span><strong>${counts.cancelled}</strong></div>`;render()}
function render(){const list=state.orders.filter(o=>group(o.status)===state.filter);$('orderCount').textContent=`共 ${list.length} 筆訂單`;$('orders').innerHTML=list.length?list.map(card).join(''):'<div class="empty">目前沒有這個狀態的訂單</div>';document.querySelectorAll('[data-filter]').forEach(b=>b.dataset.active=String(b.dataset.filter===state.filter))}
function card(o){const g=group(o.status),address=o.delivery==='7-11超商取貨'?`${o.storeName}門市 ${o.storeCode}・${o.storeAddress}`:o.homeAddress;return `<article class="order ${g}" data-order="${esc(o.orderNo)}"><div class="order-top"><h2>${esc(o.orderNo)}</h2><span class="status">${label(o.status)}</span></div><div class="order-meta"><span>${esc(o.createdAt)}</span><span>${esc(o.delivery)}</span><strong>${money(o.total)}</strong></div><div class="customer"><span>收件人：${esc(o.customerName)}</span><span>電話：<a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></span><span>${esc(address)}</span></div><p class="items">${esc(o.itemsSummary||'商品明細未載入')}</p>${o.note?`<p>備註：${esc(o.note)}</p>`:''}${g==='waiting'?`<div class="actions"><div class="ship-row"><input class="tracking-input" placeholder="輸入物流單號（必填）" autocomplete="off"><button class="ship-button" data-ship>確認出貨</button></div><div class="cancel-row"><input class="reason-input" placeholder="取消原因（選填）"><button class="cancel-button" data-cancel>取消訂單</button></div></div>`:g==='shipped'?`<div class="tracking">物流單號：<strong>${esc(o.trackingNo||'未填寫')}</strong><br>出貨時間：${esc(o.shippedAt||'')}</div>`:''}</article>`}
async function ship(article){const trackingNo=article.querySelector('.tracking-input').value.trim();if(trackingNo.length<4)return toast('請先輸入完整物流單號。',true);const button=article.querySelector('[data-ship]');button.disabled=true;try{const r=await api('adminShipOrder',{adminToken:state.token,orderNo:article.dataset.order,trackingNo});toast(r.message);await refresh()}catch(err){toast(err.message,true)}finally{button.disabled=false}}
async function cancel(article){const reason=article.querySelector('.reason-input').value.trim();if(!window.confirm(`確定要取消訂單 ${article.dataset.order}？取消後會回補庫存。`))return;const button=article.querySelector('[data-cancel]');button.disabled=true;try{const r=await api('adminCancelOrder',{adminToken:state.token,orderNo:article.dataset.order,reason});toast(r.message);await refresh()}catch(err){toast(err.message,true)}finally{button.disabled=false}}
function toast(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error-toast',error);$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,3200)}function logout(){state.token='';sessionStorage.removeItem('liuheAdminToken');$('dashboard').hidden=true;$('logoutButton').hidden=true;$('passwordButton').hidden=true;$('loginPanel').hidden=false}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openPassword(){$('passwordError').textContent='';$('passwordForm').reset();$('passwordDialog').showModal()}
function setBusy(button,busy,label){if(busy){button.dataset.label=button.textContent;button.disabled=true;button.classList.add('is-loading');button.textContent=label}else{button.disabled=false;button.classList.remove('is-loading');button.textContent=button.dataset.label||button.textContent;delete button.dataset.label}}
async function changePassword(e){e.preventDefault();$('passwordError').textContent='';const values=Object.fromEntries(new FormData(e.currentTarget).entries());if(values.newPin!==values.confirmPin){$('passwordError').textContent='兩次輸入的新密碼不一致。';return}const button=e.currentTarget.querySelector('.password-submit');setBusy(button,true,'修改中');try{const result=await api('adminChangePassword',{adminToken:state.token,...values});$('passwordDialog').close();logout();$('loginError').textContent=result.message}catch(err){$('passwordError').textContent=err.message}finally{setBusy(button,false)}}
$('loginForm').addEventListener('submit',login);$('refreshButton').addEventListener('click',refresh);$('logoutButton').addEventListener('click',logout);$('passwordButton').addEventListener('click',openPassword);$('passwordClose').addEventListener('click',()=>$('passwordDialog').close());$('passwordForm').addEventListener('submit',changePassword);document.querySelector('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;render()});$('orders').addEventListener('click',e=>{const a=e.target.closest('.order');if(!a)return;if(e.target.closest('[data-ship]'))ship(a);if(e.target.closest('[data-cancel]'))cancel(a)});if(state.token)refresh();
