(function(){
  'use strict';
  const config=window.APP_CONFIG||{};
  const els={loading:document.getElementById('loadingState'),empty:document.getElementById('emptyState'),error:document.getElementById('errorState'),errorMessage:document.getElementById('errorMessage'),section:document.getElementById('ordersSection'),list:document.getElementById('ordersList'),memberName:document.getElementById('memberName'),refresh:document.getElementById('refreshButton'),retry:document.getElementById('retryButton')};
  let appToken='';
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
  function show(name,message){['loading','empty','error','section'].forEach(key=>{els[key].hidden=key!==name});if(message)els.errorMessage.textContent=message}
  async function api(action,payload){const response=await fetch(config.API_BASE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload:payload||{}})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error((data.error&&data.error.message)||'讀取失敗，請稍後再試');return data.result}
  function displayStatus(raw){const status=String(raw||'');if(status==='已取消')return{text:'已取消',className:'status-cancelled'};if(status==='已出貨'||status==='已完成')return{text:'已出貨',className:'status-shipped'};return{text:'已收到訂單・等待出貨',className:'status-waiting'}}
  function itemRows(order){return `<li class="order-item"><span>商品明細</span><strong>${esc(order.itemsSummary||'請洽商家')}</strong></li>`}
  function renderOrder(order){const state=displayStatus(order.status);const tracking=order.trackingNo||'';const created=order.createdAt||'';return `<article class="order-card"><header class="order-head"><div><p class="order-number">訂單編號</p><h2>${esc(order.orderNo||'—')}</h2></div><span class="status-pill ${state.className}">${state.text}</span></header><div class="order-body"><ul class="order-items">${itemRows(order)}</ul><div class="order-meta"><span>訂單時間</span><strong>${esc(created||'—')}</strong><span>訂單金額</span><strong>NT$${esc(order.total||0)}</strong><span>配送方式</span><strong>${esc(order.delivery||'—')}</strong></div>${tracking?`<div class="tracking-box"><small>物流／出貨單號</small><strong>${esc(tracking)}</strong></div>`:''}</div></article>`}
  async function establishSession(){if(!config.LIFF_ID)throw new Error('尚未設定 LIFF_ID');if(!window.liff)throw new Error('LINE 登入元件載入失敗');await liff.init({liffId:config.LIFF_ID});if(!liff.isLoggedIn()){liff.login({redirectUri:window.location.href});return false}const session=await api('lineSessionCreate',{idToken:liff.getIDToken(),accessToken:liff.getAccessToken()});appToken=session.sessionToken||'';if(!appToken)throw new Error('無法建立 LINE 登入階段');return true}
  async function loadOrders(){show('loading');els.refresh.disabled=true;try{if(!appToken){const ready=await establishSession();if(!ready)return}const result=await api('myOrders',{lineSessionToken:appToken});const orders=result.orders||[];els.memberName.textContent=result.lineName?`${result.lineName} 的訂單`:'你的訂單';if(!orders.length){show('empty');return}els.list.innerHTML=orders.map(renderOrder).join('');show('section')}catch(error){show('error',error.message||'請稍後再試一次。')}finally{els.refresh.disabled=false}}
  els.refresh.addEventListener('click',loadOrders);els.retry.addEventListener('click',loadOrders);loadOrders();
})();
