(function(){
  'use strict';
  const config=window.PLATFORM_CONFIG||window.APP_CONFIG||{};
  const platformMode=Boolean(window.PLATFORM_CONFIG),params=new URLSearchParams(location.search),shop=params.get('shop')||'liuhe';
  const els={loading:document.getElementById('loadingState'),empty:document.getElementById('emptyState'),error:document.getElementById('errorState'),errorMessage:document.getElementById('errorMessage'),section:document.getElementById('ordersSection'),list:document.getElementById('ordersList'),memberName:document.getElementById('memberName'),refresh:document.getElementById('refreshButton'),retry:document.getElementById('retryButton')};
  let appToken='',idToken='',lineName='';const ORDERS_CACHE='myOrdersCache-'+shop;
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
  function show(name,message){['loading','empty','error','section'].forEach(key=>{els[key].hidden=key!==name});if(message)els.errorMessage.textContent=message}
  async function api(action,payload){const response=await fetch(config.API_BASE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload:payload||{}})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error((data.error&&data.error.message)||'讀取失敗，請稍後再試');return data.result}
  async function platformApi(){const response=await fetch(config.API_BASE_URL+'/api/orders/mine?shop='+encodeURIComponent(shop),{headers:{authorization:'Bearer '+idToken}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error?.message||'讀取失敗，請稍後再試');return{lineName,orders:(data.result||[]).map(order=>({orderNo:order.order_no,status:order.status,createdAt:order.created_at,total:order.total,delivery:order.delivery,trackingNo:order.tracking_no,itemsSummary:(order.items||[]).map(item=>`${item.product_name} ${item.quantity} 包`).join('、')}))}}
  function displayStatus(raw){const status=String(raw||'');if(status==='已取消')return{text:'已取消',className:'status-cancelled'};if(status==='已出貨'||status==='已完成')return{text:'已出貨',className:'status-shipped'};return{text:'已收到訂單・等待出貨',className:'status-waiting'}}
  function itemRows(order){return `<li class="order-item"><span>商品明細</span><strong>${esc(order.itemsSummary||'請洽商家')}</strong></li>`}
  function formatCreated(value){if(!value)return'—';const date=new Date(value);if(Number.isNaN(date.getTime()))return String(value);return new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)}
  function renderOrder(order){const state=displayStatus(order.status);const tracking=order.trackingNo||order.tracking_no||'';const created=order.createdAt||order.created_at||order.orderTime||order.order_time||'';return `<article class="order-card"><header class="order-head"><div><p class="order-number">訂單編號</p><h2>${esc(order.orderNo||order.order_no||'—')}</h2></div><span class="status-pill ${state.className}">${state.text}</span></header><div class="order-body"><ul class="order-items">${itemRows(order)}</ul><div class="order-meta"><span>下單時間</span><strong>${esc(formatCreated(created))}</strong><span>訂單金額</span><strong>NT$${esc(order.total||0)}</strong><span>配送方式</span><strong>${esc(order.delivery||'—')}</strong></div>${tracking?`<div class="tracking-box"><small>物流／出貨單號</small><strong>${esc(tracking)}</strong><button type="button" data-copy="${esc(tracking)}">複製單號</button></div>`:''}<p class="order-help">訂單有任何問題請 LINE 官方聯繫</p></div></article>`}
  async function establishSession(){if(!config.LIFF_ID)throw new Error('尚未設定 LIFF_ID');if(!window.liff)throw new Error('LINE 登入元件載入失敗');await liff.init({liffId:config.LIFF_ID,withLoginOnExternalBrowser:true});if(!liff.isLoggedIn()){liff.login({redirectUri:window.location.href});return false}idToken=liff.getIDToken()||'';const decoded=liff.getDecodedIDToken()||{};lineName=decoded.name||'';try{const profile=await liff.getProfile();lineName=profile.displayName||lineName}catch(_){}if(platformMode){if(!idToken)throw new Error('無法取得 LINE 登入憑證');return true}const session=await api('lineSessionCreate',{idToken,accessToken:liff.getAccessToken()});appToken=session.sessionToken||'';if(!appToken)throw new Error('無法建立 LINE 登入階段');return true}
  function renderResult(result){const orders=result.orders||[];els.memberName.textContent=result.lineName?`${result.lineName} 的訂單`:'你的訂單';if(!orders.length){show('empty');return}els.list.innerHTML=orders.map(renderOrder).join('');show('section')}
  async function loadOrders(){let cached=null;try{cached=JSON.parse(localStorage.getItem(ORDERS_CACHE)||'null')}catch(_){}if(cached)renderResult(cached);else show('loading');els.refresh.disabled=true;try{if(!idToken&&!appToken){const ready=await establishSession();if(!ready)return}const result=platformMode?await platformApi():await api('myOrders',{lineSessionToken:appToken});localStorage.setItem(ORDERS_CACHE,JSON.stringify(result));renderResult(result)}catch(error){if(!cached)show('error',error.message||'請稍後再試一次。')}finally{els.refresh.disabled=false}}
  els.list.addEventListener('click',async event=>{const button=event.target.closest('[data-copy]');if(!button)return;try{await navigator.clipboard.writeText(button.dataset.copy);const old=button.textContent;button.textContent='已複製';setTimeout(()=>button.textContent=old,1500)}catch(_){}});els.refresh.addEventListener('click',loadOrders);els.retry.addEventListener('click',loadOrders);loadOrders();
})();
